import pytest

import huff


@pytest.mark.parametrize('source', [
    'Hello, there!',

    '''
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
    when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
    It has survived not only five centuries, but also the leap into electronic typesetting, 
    remaining essentially unchanged. It was popularised in the 1960s with the release of 
    Letraset sheets containing Lorem Ipsum passages, 
    and more recently with desktop publishing software 
    like Aldus PageMaker including versions of Lorem Ipsum.
    ''',

    'I am a pretty, pretty princess',

    '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tristique condimentum metus sed ultrices. Donec tempus magna erat, at porta ligula pellentesque nec. Vestibulum varius augue a nisl cursus, et fermentum est tristique. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla tincidunt augue quis feugiat porta. Morbi eu magna vitae nunc laoreet placerat et eget nibh. Vivamus tristique felis sit amet ligula sodales finibus. Pellentesque mattis nulla et accumsan sodales.

Sed auctor mauris purus, id lacinia massa rutrum ac. Ut accumsan, ligula pretium bibendum porttitor, tortor massa tempor nisl, ac lacinia purus risus non odio. Aenean et sem et urna vestibulum ullamcorper. Cras massa dolor, sollicitudin vitae posuere eget, venenatis suscipit justo. Nulla lacinia condimentum tincidunt. Maecenas imperdiet pharetra est, et ultricies libero volutpat ac. Curabitur sodales ligula ac massa tempus gravida. Pellentesque bibendum neque sit amet congue ullamcorper. Aliquam congue ex nec orci lobortis porttitor. Duis pulvinar egestas lorem in efficitur. Integer tincidunt ultricies accumsan. Sed a faucibus arcu, sed tempor velit. Maecenas auctor vel arcu non feugiat.

Aliquam placerat ante felis, nec mollis magna tempor pellentesque. Nulla neque dolor, ornare at pulvinar sit amet, viverra volutpat mauris. Duis maximus nulla eros, ut posuere justo ornare ut. Maecenas ut odio nibh. Fusce in odio vel neque gravida consectetur in id orci. Phasellus aliquet mauris turpis, id suscipit purus dictum ut. Curabitur sit amet erat ut elit aliquam porttitor vitae quis ligula. Aliquam nec metus ac purus pharetra lacinia quis in lectus. Sed sollicitudin quam ut eleifend scelerisque. Sed a bibendum erat. Nulla ipsum lectus, ornare quis risus ut, vulputate bibendum nulla. Nullam iaculis ante condimentum laoreet bibendum. Nam nulla massa, laoreet sed arcu et, aliquam viverra lectus. Fusce porttitor sagittis quam quis convallis.

Etiam at viverra magna. Suspendisse nec vestibulum turpis. Maecenas tempus nunc leo, nec dictum velit vestibulum quis. Aenean imperdiet nunc elit, quis blandit nulla efficitur id. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin aliquam ut eros non bibendum. In hac habitasse platea dictumst.

Vivamus at ex sit amet est mollis vehicula sit amet et mi. Praesent sollicitudin sollicitudin ex a rhoncus. Sed varius elit sit amet turpis condimentum vestibulum. Sed at efficitur diam. Aliquam pellentesque imperdiet metus quis rutrum. Aliquam rutrum fermentum mi, in hendrerit nisl pretium id. Maecenas interdum ex ligula, nec sagittis ex porttitor non. Nam tempus nisi pulvinar sem suscipit, sed aliquet elit venenatis.
    ''',

    '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pretium efficitur libero, sit amet aliquet nunc rutrum in. Vivamus eu velit massa. Sed faucibus est velit, nec finibus nisl bibendum at. Suspendisse eu mauris sed magna posuere varius vitae a orci. Suspendisse imperdiet, risus sed aliquet malesuada, tortor velit laoreet massa, in pretium diam quam ac tellus. Fusce ac sem volutpat quam rutrum tristique. Sed metus velit, iaculis ut tellus non, pharetra facilisis ipsum. Etiam efficitur tempus orci, at eleifend erat sodales et. Vivamus tempor, dolor sit amet ultricies vehicula, ipsum tellus rhoncus mauris, sit amet fringilla nisl urna tincidunt lorem. Integer placerat bibendum nulla, eu facilisis neque tempor in.

Nunc finibus dapibus tellus, at pretium felis pulvinar vel. Etiam pellentesque tortor urna, sed mollis ex pulvinar id. Duis accumsan enim ac dolor sodales, vitae condimentum ligula imperdiet. Praesent ac lectus at neque faucibus laoreet. Nulla facilisi. Integer efficitur eros felis, sed porttitor nisl pellentesque quis. Sed tristique interdum justo ac ullamcorper. Nulla blandit quam eget odio cursus rhoncus. Morbi nisi purus, sagittis eget ipsum in, porttitor semper lacus. Donec eu leo id tortor tristique tristique ut vitae nisl. Sed tristique nisi odio, at luctus elit lobortis ac. Vestibulum eget arcu accumsan, accumsan metus quis, porttitor dolor. Aliquam efficitur vehicula enim eu commodo. Aliquam erat volutpat. Fusce interdum gravida iaculis.

Etiam iaculis dignissim mauris vitae dapibus. Aenean in malesuada dolor. Sed at sapien arcu. Vivamus vulputate massa fermentum, porta nisi at, interdum sapien. Donec felis diam, aliquam quis euismod id, rhoncus eu ipsum. Aliquam at felis sed turpis posuere rutrum a ut urna. Aliquam id quam ullamcorper, condimentum ante dapibus, rutrum dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec vitae mi imperdiet, tempor turpis ut, aliquet mauris. Nullam hendrerit fringilla ipsum, eget finibus dolor ornare sed. Sed volutpat tortor ut dui rhoncus, a gravida tellus scelerisque.

Vestibulum sed pellentesque mauris. Sed dignissim lacus et magna congue pharetra ac eget turpis. Maecenas tempus turpis metus, ut condimentum elit pharetra in. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tellus dui, volutpat tincidunt varius vel, imperdiet nec elit. Praesent vulputate sagittis finibus. Quisque fringilla eget est eget feugiat. Aliquam vehicula eros semper, viverra velit ac, posuere mi. Curabitur et venenatis nunc. Vestibulum sodales lorem orci, eget venenatis ligula feugiat quis. Nunc urna nulla, fermentum bibendum orci eu, molestie finibus dolor. Duis porta velit gravida nulla venenatis facilisis. Suspendisse justo mauris, faucibus a elementum sed, vehicula non sem. Nunc elementum dui a odio aliquet ultricies.

Phasellus luctus, sem pretium sagittis dignissim, lorem magna dignissim est, quis rhoncus leo metus mattis massa. Ut quis laoreet dui. Donec condimentum ex ac leo consequat, eget ullamcorper sem scelerisque. Fusce laoreet et ante at tristique. Sed purus nunc, aliquet sit amet ligula vel, ullamcorper vulputate odio. Nam efficitur iaculis lorem, cursus mollis sem elementum nec. Etiam dictum consequat dui, quis convallis orci mattis non. Vestibulum in egestas mauris, sit amet pretium urna. Phasellus accumsan, velit et placerat auctor, nulla odio elementum arcu, vitae aliquam massa dolor nec libero. Cras molestie massa eu mi consectetur, ut aliquam nisi venenatis. Integer mollis ex eu pharetra hendrerit.

Proin vitae nisi id nunc pharetra consequat. Integer viverra rutrum ullamcorper. Suspendisse pretium, augue vitae hendrerit blandit, nisl risus faucibus libero, at euismod leo nisi eget libero. Pellentesque et odio ullamcorper, efficitur massa at, feugiat erat. Nulla a tellus turpis. Duis pretium ex vel hendrerit imperdiet. Quisque tincidunt urna eu ex malesuada, eget rutrum sem vehicula. Quisque nec malesuada risus. Quisque ante dolor, condimentum nec erat quis, egestas fringilla diam. Suspendisse eu nulla fringilla, dapibus nunc sit amet, sodales nisl. Etiam imperdiet consequat tortor, eu congue diam bibendum nec. Pellentesque a ligula metus.

Aenean ultricies consequat tristique. Aenean tempus tristique neque in fringilla. Proin aliquet pellentesque convallis. Suspendisse id felis neque. Nam ornare mauris arcu, ut faucibus ante finibus sed. Vestibulum vitae dictum erat, in scelerisque mi. Aliquam commodo venenatis ante quis laoreet. Nunc metus lacus, fringilla et vestibulum a, pellentesque vitae enim. Aenean ac odio id ligula luctus fringilla at sit amet lectus. Mauris eleifend nibh eu tincidunt tristique. Etiam finibus diam quis enim bibendum rutrum. Sed consectetur eleifend sem sed molestie. Nunc malesuada suscipit dolor eget interdum.

Proin eget condimentum enim, at viverra est. Fusce est lectus, ornare a tellus ac, iaculis accumsan purus. Curabitur ac molestie ante, ut lobortis tellus. Quisque consequat felis non iaculis sollicitudin. Proin sit amet mollis tortor. Morbi nunc felis, finibus quis quam id, porttitor pulvinar dui. Mauris maximus tincidunt scelerisque. In sollicitudin, dui nec sagittis ornare, erat sem maximus nunc, eget sagittis metus nulla ac risus. Curabitur eleifend dolor non fermentum sodales. Curabitur tempor magna ac leo aliquam vehicula. Suspendisse consectetur dictum magna a congue. Curabitur a ante tortor. Cras eget neque vitae risus commodo congue at et libero. Vivamus quis diam vel erat interdum laoreet a et nisl.

Nunc tristique nec ex sed imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dignissim neque commodo nisi rhoncus venenatis. Sed tristique ut nisl vitae ultricies. Vestibulum vehicula consectetur molestie. Etiam tincidunt consectetur risus et blandit. Curabitur quis velit hendrerit, mattis massa vel, auctor lacus. Nullam fringilla id purus quis placerat. Ut vestibulum turpis turpis, quis pharetra ligula auctor non. Suspendisse sit amet ipsum ullamcorper, egestas mauris eu, porta turpis. Morbi iaculis pharetra rhoncus. Sed eleifend tincidunt risus lacinia condimentum.

Quisque porta enim leo, ac ultricies risus sollicitudin ac. Nam vitae magna non est rutrum suscipit vitae vel justo. Pellentesque vel iaculis orci. Nunc in dolor sodales leo mollis malesuada. Curabitur arcu ante, iaculis id vestibulum et, lacinia vulputate augue. In gravida mattis felis, id consectetur erat euismod eget. Quisque tincidunt nunc bibendum augue suscipit lacinia. Suspendisse felis ante, molestie ac orci non, eleifend ultrices risus. Integer vitae enim convallis, facilisis dui aliquet, ornare enim. Maecenas aliquet massa at mi ultricies, in imperdiet magna pulvinar. Pellentesque aliquet bibendum libero, eget malesuada velit malesuada nec. In blandit dapibus orci eu accumsan. Donec id nulla ligula.

Aenean consectetur leo quam, vel tempus leo eleifend eu. Etiam gravida nibh vel justo bibendum, vel dignissim felis varius. Donec ut gravida massa. Vivamus aliquet erat sit amet sem tincidunt hendrerit ut ac velit. Ut diam odio, pharetra quis varius non, pharetra sed massa. Aliquam maximus in ipsum ut tristique. Sed placerat orci ut arcu tempus, eget interdum neque vestibulum. Donec urna felis, venenatis porta erat a, sagittis porta nisi. Donec congue turpis et nibh vestibulum sagittis.

Vestibulum lacinia sapien nec elit accumsan, eget rutrum purus hendrerit. Phasellus ac suscipit nulla, in consequat dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut quis augue sit amet mauris ullamcorper finibus. Nunc at risus quis arcu finibus lobortis at non enim. Ut vel nunc eros. Integer elit nibh, venenatis quis tellus ac, interdum porta erat. Proin maximus est non ipsum aliquet cursus. Vestibulum sed mi condimentum, rutrum ante eget, ultrices risus. Quisque eget purus ac leo bibendum egestas in eget augue. Nunc sollicitudin at risus sed vulputate.

Curabitur pulvinar lacinia felis vitae cursus. Aliquam eu vehicula elit. Sed feugiat, lectus at commodo lacinia, orci magna laoreet lectus, facilisis condimentum urna neque non sapien. Aenean porttitor dignissim ipsum sit amet feugiat. Vestibulum sed lacus eget sem rhoncus ullamcorper quis nec leo. Aenean malesuada nisi vitae ornare molestie. Sed ornare a tellus eget pulvinar. Curabitur egestas est nec magna posuere elementum. Quisque sit amet arcu massa. Donec lobortis turpis vel leo finibus, sed egestas lorem condimentum. Etiam feugiat ex a nulla imperdiet, quis pretium magna tempus. Donec elit felis, sodales et turpis quis, mollis laoreet mauris.

Aenean ultricies risus ut orci faucibus scelerisque sit amet at lacus. Cras pulvinar ante nec mauris tristique interdum. Quisque in magna ultricies, rutrum velit quis, luctus mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam congue tristique purus. Phasellus congue purus quis urna porttitor, pretium tempus ipsum tincidunt. Aenean ut odio condimentum, sodales ligula fringilla, placerat nisl. Vivamus posuere blandit ligula eget lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed blandit ligula a elit interdum, ac cursus velit dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque accumsan nisl interdum justo faucibus cursus. Pellentesque laoreet suscipit nisl.

Nunc felis nulla, blandit sed ultricies in, blandit non lacus. Proin et condimentum felis, eget luctus dolor. Sed et tempor odio. Nullam rutrum massa id lobortis accumsan. Mauris blandit porta nibh et commodo. Vestibulum nibh dui, blandit quis eros finibus, volutpat luctus risus. Nam eget neque quam. Ut sollicitudin dui ac facilisis hendrerit. Quisque hendrerit vulputate rhoncus. Aliquam elementum eleifend massa a dictum. Sed consequat, urna luctus sodales rhoncus, nisi purus pulvinar felis, a porta orci urna et ante. Donec sodales non massa nec pharetra.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus id rhoncus nisi. Vestibulum sit amet semper augue. Proin quis congue est. In ac nulla non arcu commodo tempor id eget elit. Nulla molestie suscipit eros ut iaculis. Integer maximus neque sed velit efficitur tincidunt. Donec sollicitudin ligula eu massa iaculis, ut porta lectus rutrum.

Curabitur ligula nibh, viverra id ex quis, suscipit malesuada nulla. Vivamus vulputate elit non convallis rutrum. Quisque at erat id dui pulvinar posuere. Suspendisse blandit purus vel nisl tincidunt euismod. Integer non hendrerit justo, quis convallis purus. Nullam maximus leo a commodo volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut iaculis quam ac rutrum imperdiet. Nam interdum urna sed tincidunt porttitor. Curabitur suscipit risus at nibh iaculis volutpat. Nullam sollicitudin consectetur turpis id rhoncus. Nulla facilisi. In consectetur mi eu purus accumsan, quis lacinia lectus sollicitudin. Donec blandit dapibus cursus. Vivamus ultricies, enim ultrices pellentesque gravida, velit tortor auctor augue, sed hendrerit libero enim eget velit.

Quisque eget ex non diam convallis semper. Etiam eget tellus ac magna dignissim rutrum fermentum et dui. Praesent viverra nisl ac enim tempus bibendum. In vehicula sapien at massa convallis, non maximus lectus dignissim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur vel dui sit amet elit interdum egestas. Sed sit amet nibh eget lorem efficitur pellentesque.

Sed vitae consequat risus. Phasellus dictum commodo erat. Curabitur at erat dui. Maecenas nec nisi vel risus aliquet viverra. Donec ullamcorper bibendum iaculis. In vel porttitor metus. In sodales tempus risus vitae eleifend. Phasellus eleifend malesuada ultrices.

Etiam nec sem vitae ligula rhoncus porttitor. Etiam magna nibh, sodales a est ut, feugiat consectetur libero. Curabitur congue ex commodo, aliquet libero eget, aliquam massa. Maecenas lobortis aliquam magna, at aliquam est lobortis id. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla quis ipsum accumsan, scelerisque orci ac, pellentesque justo. Maecenas porttitor elementum velit quis cursus. Suspendisse venenatis maximus eros, sed ornare est finibus ac. Vestibulum nunc mauris, malesuada in dapibus sit amet, aliquam eget justo. Pellentesque mollis ultricies urna, vel consequat eros scelerisque vel. Fusce tincidunt felis vitae mi tincidunt placerat. Donec nec blandit est.

Donec eget tortor sed diam euismod facilisis. In feugiat sit amet nibh vitae egestas. Vestibulum faucibus fermentum magna, at pharetra lorem placerat vel. Fusce non dolor euismod, condimentum arcu eu, convallis tortor. Suspendisse potenti. Donec eget urna vitae enim eleifend pulvinar vitae sodales eros. Cras vitae magna neque. Aliquam nunc neque, pharetra vel sapien id, aliquet suscipit sapien. Proin fringilla accumsan metus eu cursus. Integer vel condimentum metus. Nunc lobortis non mi sed accumsan. Nam vitae suscipit nibh. Curabitur pharetra nisl vel felis semper consectetur.

In sed mauris posuere justo consectetur tincidunt. Nam tristique bibendum ligula. Vestibulum tincidunt massa ante, eu ultrices quam auctor et. Etiam dictum eros elit. Quisque eu sagittis lacus, non hendrerit dui. Aenean auctor nulla dignissim ullamcorper condimentum. Sed in suscipit lorem. Ut mattis varius nibh ac dapibus. Pellentesque pulvinar dolor vel ante volutpat, gravida sollicitudin erat condimentum. Sed mollis dapibus dignissim. Duis metus elit, placerat sit amet dignissim ac, hendrerit a risus. Praesent et vehicula nulla, a mattis tortor. Fusce sit amet gravida diam, ut dictum nulla. Quisque suscipit, augue vestibulum efficitur porttitor, lorem neque varius elit, et sagittis massa nunc quis purus. Quisque vulputate velit mi, vel feugiat ipsum vestibulum eget.

Ut vitae massa magna. Aliquam erat volutpat. Mauris eleifend eget ipsum quis mollis. Vestibulum facilisis eleifend dolor, sed pellentesque augue imperdiet id. Proin a cursus ligula. Praesent enim metus, lobortis at volutpat sed, fermentum non risus. Sed pretium purus quis erat accumsan tincidunt. Sed et nulla eu nisl elementum eleifend. Vestibulum lobortis velit tortor, at placerat magna pharetra vitae. Vestibulum eu consectetur sem, at tempus erat.

Donec ante augue, ullamcorper sit amet quam ut, egestas luctus eros. Aliquam augue est, gravida id lacus sed, commodo gravida nisl. Praesent pharetra ex iaculis, iaculis lorem nec, volutpat tortor. Etiam vitae volutpat felis, at bibendum massa. Proin nec neque justo. Proin sagittis, ligula eget blandit elementum, mauris nisl molestie sapien, et laoreet ligula tellus ac ligula. Aenean sapien ligula, viverra non nulla nec, posuere elementum ligula. Phasellus nec elementum erat, a condimentum nulla. Quisque scelerisque lobortis iaculis. Donec scelerisque sit amet lacus at facilisis.

Suspendisse potenti. Aenean finibus velit at nulla commodo, in tempus ligula auctor. Integer vitae mi nisl. Ut egestas sem urna, quis malesuada orci gravida non. Ut pharetra vitae nunc et gravida. Duis condimentum porta consectetur. In quis odio in lacus vehicula euismod.

Proin ornare enim quis egestas tristique. Suspendisse ligula metus, vulputate in aliquam quis, gravida in tellus. Quisque pulvinar libero porttitor posuere semper. In efficitur purus purus, vel vulputate magna malesuada eget. Curabitur eu odio tortor. In eget odio in massa consequat sollicitudin. Nulla dapibus odio ac congue pretium. Donec ultricies, erat vitae facilisis feugiat, magna ipsum condimentum sapien, ac placerat elit eros vitae ligula. In bibendum, erat vitae tempus feugiat, nibh arcu ullamcorper enim, hendrerit vestibulum nunc libero quis urna. Mauris placerat mollis nunc, non fringilla enim sodales ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam bibendum ligula porttitor efficitur scelerisque. Fusce hendrerit leo nec metus consequat, a gravida nibh bibendum. Vestibulum ac tellus pulvinar, mattis eros nec, pulvinar nulla. Quisque placerat arcu id euismod porttitor. Maecenas eu convallis dui. In vehicula mauris non ante laoreet, a aliquet purus porta. Aliquam lobortis est diam, a imperdiet nisi dapibus ut. Etiam vitae sapien ut ex consectetur porta. Aliquam sed pharetra ligula. Proin tempor lorem a ipsum faucibus consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam porttitor laoreet nisl, eget lobortis mi venenatis at. Duis quis rhoncus neque, quis tempus lorem. Vestibulum euismod erat diam, at accumsan eros euismod in.

Cras risus dolor, facilisis at justo nec, elementum aliquam lorem. Mauris tincidunt molestie orci eget mattis. Praesent facilisis tortor lacus, at sagittis nisl sollicitudin sed. Nam condimentum molestie sapien, et volutpat mi blandit et. Ut dictum turpis quis orci maximus, at venenatis tellus lacinia. Mauris placerat lectus sed sapien ultrices gravida. Vivamus purus dolor, interdum tempor lorem quis, faucibus bibendum est.

Sed sit amet purus ac ipsum auctor condimentum dictum id erat. Morbi a lacus iaculis, rutrum dolor non, dictum arcu. Phasellus condimentum posuere hendrerit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque elementum, ex sed accumsan vehicula, urna nisl luctus magna, ac condimentum nisl ligula sit amet massa. Aenean nisi lectus, dictum ac sem eget, consectetur accumsan augue. Mauris ac sodales quam. Nulla et euismod nibh. Donec ac porttitor urna. Duis venenatis nisl massa, eu commodo erat imperdiet nec. Morbi tincidunt neque sit amet sodales mattis. Donec eros arcu, volutpat non tellus sit amet, accumsan mattis ligula. Vivamus consequat, lacus vitae mollis mattis, odio arcu dictum enim, a aliquet arcu est ut nisl. Nam sed commodo orci. Nam non libero ex. Proin pellentesque laoreet aliquam.

Cras dapibus volutpat mi posuere pulvinar. Suspendisse hendrerit, augue sed rutrum eleifend, tortor magna venenatis orci, eget malesuada metus mauris nec libero. Phasellus aliquet ante ut nulla tristique, nec pretium lacus feugiat. Mauris elementum commodo diam et blandit. Sed tempor elit nunc, a volutpat lorem ornare in. Mauris sed justo turpis. Cras vitae tortor aliquam, interdum est a, malesuada metus. Fusce augue mi, egestas ut faucibus in, pellentesque sit amet justo. Praesent pulvinar magna non nibh accumsan, sit amet aliquet ex vulputate. Curabitur dictum ipsum ultrices tincidunt egestas. Phasellus vitae interdum magna.

Sed ante elit, porttitor ut mi sed, interdum tincidunt mauris. Mauris fermentum dictum ex, at lobortis odio tincidunt a. Pellentesque ullamcorper ipsum non malesuada tempus. Fusce malesuada ullamcorper maximus. Morbi suscipit ante eu justo mollis, et posuere eros laoreet. Nulla sed lacus dolor. Aliquam mollis elit sit amet ipsum fringilla, auctor auctor sem interdum. Aenean ullamcorper iaculis augue at consectetur. Ut blandit tortor at dui porta accumsan. Sed at est laoreet, pulvinar dolor sed, lobortis est. Pellentesque non ligula nec nibh consequat sollicitudin. Fusce nec pulvinar ipsum. Maecenas tincidunt, elit quis blandit facilisis, risus tortor fermentum nunc, ac imperdiet ligula ipsum sed enim. Vestibulum porttitor ex quis nulla auctor, id hendrerit lacus luctus. Vestibulum ultrices, est vitae vulputate aliquet, dui tellus finibus neque, ac hendrerit felis urna sed orci. Donec non tincidunt ipsum.

Donec id congue tellus, vel ornare mauris. Nullam et fermentum libero. Nulla vitae convallis purus. Vivamus feugiat sed elit scelerisque condimentum. Duis hendrerit placerat quam, ut commodo eros porta sit amet. Maecenas ut nunc mauris. Maecenas faucibus ante tellus, eget tristique diam dignissim in. Donec ac velit condimentum, hendrerit metus sit amet, efficitur neque.

In eu lacus mattis nulla elementum aliquam eget sed odio. Mauris dolor tellus, facilisis ut lorem nec, molestie consectetur purus. Vivamus diam augue, faucibus quis tincidunt sed, semper nec urna. Morbi molestie odio hendrerit ipsum suscipit, id rutrum justo hendrerit. In in tellus sit amet urna malesuada cursus a eget ex. Ut molestie molestie eros, id mollis neque vehicula at. Morbi viverra tortor quis faucibus lacinia. Fusce non ornare dolor. Pellentesque non est mattis, sagittis lectus a, mattis nibh. Curabitur eu sagittis lectus. Etiam sed fermentum orci, in suscipit quam.

In ac sapien nisi. Nulla facilisi. Ut condimentum lectus ligula, sed rhoncus enim ornare quis. Pellentesque malesuada, dui at rhoncus accumsan, felis ipsum tincidunt lorem, nec lobortis diam sapien et urna. Sed ac viverra odio, eu porttitor urna. Donec tristique enim leo, id mollis libero lacinia non. Praesent id aliquet nibh. Vivamus sit amet nisl accumsan dui elementum vehicula nec sit amet eros. Nam feugiat euismod metus ac accumsan. Suspendisse interdum congue tellus, a ultrices nisi luctus ut. Suspendisse ornare dui a lacus fringilla aliquam. Proin dignissim imperdiet fringilla. In ac odio ac leo dapibus tristique id a nisl. Aliquam malesuada est sed est hendrerit placerat.

Praesent et arcu blandit, mollis massa vitae, consectetur eros. Aliquam mattis, urna non tempor tincidunt, ex eros cursus tortor, a scelerisque elit turpis at nibh. Praesent consectetur faucibus nunc, sit amet fringilla purus ultricies aliquam. Duis odio neque, efficitur eu imperdiet at, aliquam sed nisl. Integer vitae facilisis augue, at dictum leo. Duis id risus id tortor aliquet tempor. Etiam enim dui, pretium non nisl a, tristique volutpat leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac fringilla augue. Pellentesque eu leo semper purus viverra hendrerit non tristique magna.

Nunc tempor dignissim erat, a pharetra augue auctor vitae. In condimentum mi quis urna posuere, non lobortis nibh aliquam. Donec eget lorem id purus malesuada fermentum. Vestibulum eget interdum urna, nec dapibus risus. Vivamus sit amet magna at massa facilisis iaculis eu quis sapien. Fusce porta orci non vestibulum placerat. Proin facilisis feugiat nunc vel aliquet. Suspendisse scelerisque dolor purus, in euismod ex cursus nec. Fusce velit purus, tempor vel magna non, tempus lacinia sem. Etiam in orci egestas, egestas odio eu, faucibus felis.

Duis libero velit, hendrerit eget suscipit vel, egestas id orci. Integer accumsan, sem vel rhoncus vestibulum, leo lectus ornare leo, nec fringilla augue risus eget augue. Nulla facilisis commodo ex eget imperdiet. Maecenas nec mauris nec arcu rhoncus ultrices. Aenean faucibus pretium lorem, ut consectetur lectus rhoncus eu. Nam in augue nunc. Maecenas fringilla placerat tincidunt. Pellentesque dui neque, vehicula eu lacus vitae, lacinia ullamcorper nisi. Aenean a massa lobortis, placerat elit et, convallis risus. Curabitur tempor metus eu magna volutpat rhoncus. Cras pulvinar at ante a tincidunt.

Sed erat ligula, tincidunt a hendrerit at, interdum nec ex. Proin mattis libero facilisis massa cursus ullamcorper. In tristique ex in nibh rutrum consequat. Nunc nisl mauris, facilisis in hendrerit a, bibendum condimentum quam. Pellentesque vehicula, dui eu tincidunt auctor, nulla leo gravida risus, id feugiat justo nibh in turpis. Curabitur ullamcorper accumsan lectus, non pellentesque nunc fermentum quis. Suspendisse rutrum nunc diam, in fringilla purus tempor non. Sed in mi imperdiet, mattis augue in, gravida nisl. Duis dolor nulla, pretium eu sem sit amet, condimentum aliquam purus. Donec aliquet felis ac mattis fermentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse sed justo tincidunt, finibus diam non, hendrerit augue. Aenean lectus dolor, convallis a cursus a, consectetur at ligula. Morbi ultricies lacus id dolor dignissim tincidunt.

Etiam at arcu eu diam dictum porta vel at mi. Donec congue risus in nisi bibendum, sit amet pellentesque turpis sollicitudin. Cras laoreet accumsan dolor eget congue. Nam feugiat vel augue sed finibus. Nullam imperdiet ultricies efficitur. Sed molestie maximus cursus. Nam bibendum augue ex, eu blandit dui blandit at. Fusce blandit pretium elit condimentum vestibulum. Integer mi mi, auctor at libero sed, maximus maximus purus. Aliquam lacinia mauris sit amet interdum consectetur. Donec id sollicitudin tortor.

Fusce a consequat massa, vestibulum posuere sem. Nullam venenatis ex vel tempus malesuada. In non efficitur magna. Phasellus vitae lectus dapibus, eleifend felis eu, imperdiet elit. Etiam imperdiet nulla placerat malesuada consectetur. Praesent laoreet, elit quis aliquet commodo, nulla erat blandit mauris, ut convallis purus sem id nulla. Nunc cursus aliquam tellus, in semper dui luctus at. Vestibulum et leo libero. Nunc in tortor sodales risus sagittis dignissim. Nam mollis risus massa, et dictum magna molestie ut. Duis nisi ipsum, dictum quis metus nec, imperdiet fermentum lectus.

Vestibulum tellus diam, congue ut ultrices eget, eleifend et eros. Cras sed urna tempus, ultricies lacus et, sagittis dui. Vestibulum vitae orci ac eros sodales congue et non justo. Ut nec porttitor velit. Pellentesque condimentum sed nisi a tempor. Suspendisse rutrum ex sem, quis faucibus sapien pellentesque eu. Pellentesque mattis facilisis libero, eget pretium justo vehicula id. Donec ac pharetra metus. Donec vel erat eget justo gravida fermentum. Sed non scelerisque mauris, vel faucibus nisi. Pellentesque id finibus massa. Aliquam suscipit quam leo, eget pharetra tortor ullamcorper eget. Mauris vel consequat enim. Fusce aliquet arcu eu sagittis pretium.

Suspendisse sed tortor at ante tristique tempor. Aenean vehicula in risus non pretium. Curabitur fermentum feugiat orci ut sagittis. Donec pretium massa quis ante vulputate scelerisque. Aenean eget arcu malesuada, varius tellus ut, fringilla diam. Nunc vulputate vel arcu a ultricies. Duis in pellentesque augue. Aenean dictum vel massa id consequat. Aenean id felis vitae nisi ultricies hendrerit. Mauris vel odio quis ligula facilisis suscipit et condimentum dui. Aliquam erat volutpat. Etiam a eleifend ligula. Suspendisse pretium nisl augue, sed finibus diam laoreet ac. Etiam laoreet euismod justo vitae imperdiet.

In pulvinar faucibus tortor id tincidunt. Proin quam lacus, cursus interdum neque vel, congue mollis augue. Ut venenatis porttitor lacinia. Morbi pretium quis lacus et suscipit. Nam egestas augue in quam posuere condimentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec eget sagittis nunc. Duis vel elit ut turpis hendrerit luctus eu id dolor. Pellentesque interdum mauris vel iaculis pretium. Nulla facilisi. Curabitur risus sapien, egestas eget leo sed, semper convallis sem.

Integer pellentesque rutrum mattis. Sed sodales, ipsum efficitur luctus molestie, diam urna eleifend ex, et gravida mauris eros et velit. Cras nisi tortor, faucibus quis facilisis ac, iaculis sit amet magna. Nunc viverra erat nec ante vehicula efficitur. Maecenas euismod fermentum nunc nec fermentum. Pellentesque consectetur eros quis risus rutrum fermentum. Maecenas ac nisl in risus accumsan fermentum. In euismod tortor id neque tincidunt, at aliquam nibh pulvinar. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas sapien lectus, tincidunt at convallis at, posuere nec justo. Ut finibus volutpat erat in elementum. Vivamus faucibus, neque sed accumsan lobortis, eros orci consectetur eros, et dictum mi mauris ac augue. Vivamus eu elit vel neque rutrum porta sodales in arcu. Quisque ac lacinia justo, eu luctus eros.

Donec tellus est, imperdiet et hendrerit non, mattis vel libero. Cras interdum, erat in iaculis tempor, ante orci commodo neque, in dictum enim erat eu arcu. Maecenas ullamcorper nulla erat, suscipit rutrum metus fringilla sit amet. Sed tempor, erat sit amet aliquam fringilla, ex massa consectetur lectus, sed placerat dui mi non sem. Morbi consequat accumsan enim at tristique. Morbi ex tortor, sagittis id quam sit amet, dapibus eleifend nisi. Suspendisse egestas feugiat sem et iaculis. Aliquam vel nulla sit amet risus sollicitudin iaculis sed a mauris. Duis dignissim quis tellus sed consequat. Quisque ut metus mollis, tempor ligula non, laoreet enim. Aenean aliquam fermentum dolor, non laoreet nunc pretium quis. Nullam hendrerit tempor lacus, et bibendum libero tincidunt quis. Mauris dictum diam ac tempus lacinia. Phasellus at maximus ligula. Aliquam erat volutpat. Donec finibus metus eu pharetra efficitur.

Integer eleifend fringilla mattis. Donec ultrices, est ac rhoncus condimentum, ligula erat pharetra lectus, nec ultrices diam neque a ante. Nullam eros urna, dapibus eget erat sit amet, feugiat tempus enim. Cras in neque massa. Fusce urna urna, dignissim a rhoncus sit amet, bibendum id nunc. Sed in neque vel metus hendrerit dignissim. Nunc consequat nibh quis nisi scelerisque ornare. Donec placerat, nunc et blandit cursus, ligula risus elementum nunc, quis venenatis arcu velit blandit nulla. Nunc in mauris eget turpis tempus elementum quis eu enim. Ut iaculis mattis neque et blandit. Vivamus tincidunt posuere lorem, id malesuada tortor iaculis ut. Aliquam et sapien ac neque mattis posuere vitae eget metus. Nam sed urna urna. Donec eu nibh neque.

Nunc venenatis maximus elit, sit amet vehicula sem. Integer imperdiet justo leo, ut eleifend metus malesuada nec. Nunc suscipit ligula id placerat posuere. Suspendisse molestie, dui id tincidunt laoreet, leo magna vestibulum tortor, sit amet feugiat arcu ipsum et felis. Cras facilisis erat ut ligula porta, egestas aliquet ex interdum. Donec id sollicitudin eros. Maecenas euismod finibus purus, non vestibulum augue placerat et. In nec auctor tortor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec non risus laoreet, ultrices enim vel, lacinia tellus.

Aliquam vel neque ipsum. Suspendisse id tortor in arcu vestibulum sollicitudin. Cras faucibus augue vitae tortor aliquam accumsan. Nam sit amet nisi dui. Nullam at mauris ultricies, dictum purus eget, lobortis ipsum. Nullam volutpat lacus ac ex ornare interdum. Nulla eu diam vel purus aliquam tincidunt. Proin vel pharetra tortor. Maecenas eget turpis nec mauris dignissim laoreet. Quisque diam nibh, blandit a massa a, lobortis bibendum arcu. Suspendisse et egestas ante, eget vulputate diam. Vestibulum eget urna metus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis malesuada quam est, dignissim mattis turpis pellentesque eget. Praesent at volutpat erat, non volutpat urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Duis iaculis id mauris vitae imperdiet. Maecenas dapibus suscipit augue, nec scelerisque turpis tempus sit amet. In in felis efficitur, consequat velit eu, porta velit. Fusce blandit molestie hendrerit. Vestibulum interdum vestibulum ornare. Etiam bibendum ac velit vitae hendrerit. Aliquam erat volutpat. Quisque in purus blandit, consectetur ipsum quis, interdum sem. Proin varius tincidunt justo nec vestibulum. Maecenas sed lorem leo. Integer pretium massa id lorem lobortis, quis luctus enim malesuada. Nullam vel dapibus nulla. Mauris nunc risus, bibendum vitae nulla quis, hendrerit molestie est. Cras a blandit lacus. Sed varius nisl id dapibus venenatis. Proin varius, purus eu ullamcorper imperdiet, leo sem posuere tortor, nec sodales massa sapien ac elit.

Pellentesque sollicitudin scelerisque velit sit amet iaculis. Sed nulla nulla, consequat vel ex sit amet, consequat lobortis dolor. Duis sed commodo orci. Aenean eget diam at neque vulputate lacinia. Duis a pharetra augue. Nullam suscipit nisi non sem ultricies condimentum. Nunc tempor tempor ligula. In pulvinar lectus ipsum, ut ornare dui iaculis eget. Aliquam a eros auctor mauris blandit congue. Cras eleifend sit amet lectus euismod vulputate.
    '''
])
def test_decoding_encoded_string_equals_source(source: str):
    encoded = huff.encode(source)
    decoded = huff.decode(encoded)

    compression_ratio = (len(source) - len(encoded)) / len(source)
    print()
    print(f'Compressed {len(source)} bytes to {len(encoded)} bytes ({compression_ratio * 100:.0f}% compression)')
    print()

    expected = source
    actual = decoded
    assert expected == actual
